name: Rails Tests

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      # Use postgres for the host here because we have specified a container for the job.
      # If we were running the job on the VM this would be localhost
      DATABASE_URL: postgres://postgres:@postgres:5432/test
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install PostgreSQL 11 client
      run: |
        apt-get -yqq install libpq-dev

    - name: Install Yarn
      run: |
        npm install yarn -g

    - name: Build App
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install
        bin/rails db:setup
        bin/rails webpacker:compile

    - name: Run Tests
      run: bundle exec rails test
